
# Name of your site (displayed in the header)
name: H&A
title: H&A
language: html "en"
email: me@syedhassanali.com

# Short bio or description (displayed in the header)
description: 
keywords: 

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: 
# Your website URL 
# Used for Sitemap.xml and your RSS feed
url: 
     
baseurl: 

